server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.auv.entity

memcache:
  servers: 127.0.0.1:11211
  failover: true
  initConn: 100
  minConn: 20
  maxConn: 1000
  maintSleep: 50
  nagel: false
  socketTO: 3000
  aliveCheck: true

spring:
  datasource:
    username: sa
    password: Embed-212!2018
    url: jdbc:mysql://211.87.227.223:8306/lawknowledge?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  data:
    neo4j:
      uri: bolt://211.87.227.223:7687
      username: neo4j
      password: root


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
    servlet:
      content-type: text/html


